In [103]:
import numpy as np
import plotly.graph_objects as go

In [28]:
#exercise 3-1
def lwc(v, s):
    scal_list = list(s)
    vectors = np.array(v)
    Temp = np.zeros(3)
    for i in scal_list:
        Temp += vectors[scal_list.index(i)] * i
    return Temp

In [29]:
lwc([[4,5,1],[-4,0,-4],[1,3,2]],[1,2,-3])

array([ -7.,  -4., -13.])

In [10]:
l1 = 1
l2 = 2
l3 = -3
v1 = np.array([4,5,1])
v2 = np.array([-4,0,-4])
v3 = np.array([1,3,2])
l1*v1 + l2*v2 + l3*v3

array([ -7,  -4, -13])

In [30]:
#exercise 3-2
lwc([[4,5,1],[-4,0,-4],[1,3,2]],[1,2,-3,4]) #adding more scalars

IndexError: index 3 is out of bounds for axis 0 with size 3

In [32]:
lwc([[4,5,1],[-4,0,-4],[1,3,2],[1,2,3,4]],[1,2,-3]) #adding a vector with added dimentionality

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

In [112]:
#exercise 3-3
def rpss(v):
    v_set = np.array(v)
    s = np.random.random_integers(low=-4,high=4, size=100)
    sub = []
    for i in v_set:
        for j in s:
           sub.append(i*j) 
    return np.array(sub)

In [115]:
rp_sub = rpss([[1,3]])
rp_sub[:10]

/tmp/ipykernel_4524/3778078111.py:4: DeprecationWarning:

This function is deprecated. Please call randint(-4, 4 + 1) instead



array([[  3,   9],
       [ -4, -12],
       [ -2,  -6],
       [ -4, -12],
       [  1,   3],
       [ -4, -12],
       [  1,   3],
       [  4,  12],
       [ -1,  -3],
       [  3,   9]])

In [113]:
rp_sub2 = rpss([[3, 5, 1],[0, 2, 2]])
rp_sub2[:10]

/tmp/ipykernel_4524/3778078111.py:4: DeprecationWarning:

This function is deprecated. Please call randint(-4, 4 + 1) instead



array([[-3, -5, -1],
       [ 3,  5,  1],
       [ 9, 15,  3],
       [ 3,  5,  1],
       [ 3,  5,  1],
       [ 6, 10,  2],
       [ 0,  0,  0],
       [ 3,  5,  1],
       [ 3,  5,  1],
       [ 6, 10,  2]])

In [114]:
fig = go.Figure( data=[go.Scatter3d(
x=rp_sub2[:,0], y=rp_sub2[:,1], z=rp_sub2[:,2],
mode='markers' )])
fig.show()