In [2]:
import numpy as np

In order to use numpy library we need to add to our code. Usually we add it as np. short for numpy.

In [ ]:
python_list = [1,2,3]
np_array = np.array([1,2,3]) #1D array

We choose to use numpy arrays instead of python list to display and hold our data. With numpy arrays can represent vectors better and we can take some actions on arrays with the delighting result, that the python lists can't represent.(we'll see more example on this subject)

In [ ]:
v = np.array([[1,2,3]]) #row vector
w = np.array([[3],[4],[5]]) # column vector

Here we specify our vectors. There's a set of brackets to group all the outcome together and each aditional [] indicates a row.

In [ ]:
print(np_array.shape)
print(v.shape)
print(w.shape)

shape(): this function displays the orientation of the array. for 1D arrays we will only see one number in the parantesses that shows the number of elements in it. for row vectors and column vectors, we'll see number of row and colums.

In [ ]:
'''
Mathematical fucntions on vectors
'''
v + w #vector addition

alright! First let's see what a vector is; A vector is a straight line with magnitude and angle. But in linear algebra we basically have an ordered list of numbers or values and putting them together gives us a vector. In linear algebra we have some rules for vectors that doesn't allow us to do some certain opperations. For instance, we can't add two vectors with differend orientation. because in addition we are supposed to add the corresponding elements. But in the code implementation we'll see a slightly differend attitude. try adding two vectors with different orientation by running the following block.

In [2]:
a = np.array([[1,2,3]]) #row vector
b = np.array([[4,5,6]]).T #column vector
a + b
#now try it for subtraction!

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

Multiplication/devision
for multiplying you simply can use the * sign and for devision use /
you also can multiply a vector by a scalar number simply by multiplying it.

In [ ]:
print(a * b)
print(a / b)

Multiplying a vector by a scalar changes the magnitude and angle(180 degrees if the scalar is a negative number). 

In [ ]:
#averaging vectors
#add N vectors and devide them by N or multiply them by 1/N

dimentionality and magnitude or length of a vector
We can calculate mathematical magnitude of a vector by np.linalg.norm() function and if we can use len() we will be able to get the dimentionality of that vector.

In [ ]:
np.linalg.norm(a) , np.linalg.norm(b) , len(a) , len(b) #magnitude and length of vecor a and vector b

Dot Product
dot product is sum of corresponding elements multiplication. in other words, multiplying corresponding elements of 2 vectors and adding the resulting values together. It is used for mapping and measuring the similarity between two vectors.to use dot notation you simply call dot() method from Numpy.
np.dot()
the output will be a scalar number. We also can multiply vectors by an scalar before dot product.

In [ ]:
np.dot(a, b) , np.dot(3*a, b) #a multiplied by 3

dot product is distributive, just like the equations in basic math: a(b+c)= ab + ac
dot notation is possible only on the vectors of the same dimension.

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([6,5,6])

num1 = np.dot(a, b+c)
num2 = np.dot(a,b) + np.dot(a,c)
num1 , num2,len(a), len(b), len(c)

as you notice the values of num1 and num2 are equal.

Vector Set
A vector set is a collection of vectors and we represent it like below:
V={v1, v2, ...,vn}
vector sets can be finite and infinite.

Linear wighted combination
this is a way to mix the variables of various matrices(matrices of the same dimension)
We simply multiply a vector by a scalar and add them all up.
w = s1 * v1 + s2 * v2 +...+sn * vn

In [ ]:
l1 = 1
l2 = 2
l3 = -3
v1 = np.array([4,5,1])
v2 = np.array([-4,0,-4])
v3 = np.array([1,3,2])
l1*v1 + l2*v2 + l3*v3

Broadcasting
Broadcasting is a technique in algebra that demonstrate the idea of taking one element of a matrix and multiplying it to every other element of the other matrix. in numpy to access broadcasting we use np.outer() function. as you have guesed, size of neither matrices matter.

In [7]:
a = np.random.randn(2,2)
b = np.random.randn(3,3)
np.outer(b,a) #size of the product will be len(b)xlen(a)

array([[ 0.96292889, -0.69759167,  0.08486323, -1.25508289],
       [-1.57120306,  1.13825452, -0.13847063,  2.04790831],
       [-0.07656312,  0.05546598, -0.00674753,  0.09979248],
       [-1.55895046,  1.12937816, -0.13739081,  2.03193826],
       [-0.10390541,  0.07527404, -0.00915722,  0.13543047],
       [ 0.92315277, -0.66877595,  0.08135775, -1.20323864],
       [-0.1347438 ,  0.09761484, -0.01187501,  0.17562526],
       [ 1.09235529, -0.79135434,  0.09626963, -1.42377745],
       [-0.25920484,  0.18778037, -0.02284381,  0.33784796]])

Correlation and Cosine similarity
a single number that detemines the relationship between 2 variables. this number is between -1 and 1. each value has a unique meaning. -1 or perfect negative shows a negative linear relationship. +1 or perfect positive shows positive linear relationship and 0 means no linear relation ship. in practice files you'll see the implementation of pearson correlation coefficient and cosine similarity.

In [20]:
m = np.random.randn(1,2)
n = np.random.randn(1,2)
np.corrcoef(m,n)

array([[1., 1.],
       [1., 1.]])

Time Series filternig and Feature Detection
the mechanism of filtering is to find the dot product between time series and kernel.
Kernel: is a template used to create  anothe series from the main one based on the matching parts such as sharp edges, particular waveforms, smooth function, etc.
kernel doesn't cover the whole time series so we compute the dot product of a small part and move the kernel to the right to compute next section.

______________________________________________________________________________________________________________________________________

K-means Clustering
is a method of clustering various multivarient data into a small group vased on the minimizing group center. It is basically choosing a number of centroids and computing the distance between our data and that centroid and assigning it to the group.

Algorithm Steps:
1. initialize centroids
2. compute Euclidean distance between the observations and centroids
3. assign each data to the group with the closest centroid
4. update each centroid as the average of all data assigned to it
5. repeat 2-4



*** End of Chapter 4 ***